[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "gigachain"
version = "0.0.2"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "langchain>=0.0.264",
]

[tool.setuptools.packages]
find = {}